import PlayerPositionApi from './PlayerPositionApi';

export default interface PlayerInfoApi {
	id: number;
	name: string;
	firstname: string;
	lastname: string;
	birthplace: string;
	birthdate: string;
	sex: string;
	email: string | null;
	phone: string | null;
	isprivate: number;
	permissions: string | null;
	admincurseasonid: number | null;
	streetaddress: string | null;
	postcode: string | null;
	city: string | null;
	documentcertificate: string | null;
	datecertificate: string | null;
	doctor: string | null;
	approvalnumber: string | null;
	haspassword: boolean | null;
	photo: string;
	nationality: string | null;
	nationality2: string | null;
	nationality3: string | null;
	height: number;
	grip_throw: string | null;
	selectionNT: string | null;
	selectionNTU19: string | null;
	age: number;
	licenseOptions: string | null;
	nat1: string;
	licencenumber: number | null;
	nat2: string;
	nat3: string;
	clubid: number;
	clubname: string;
	clublogo: string;
	position: PlayerPositionApi[];
	number: number;
	grip: string;
}
